services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    restart: always
volumes:
  jenkins_home:
